import { Merienda } from "next/font/google";

import "./globals.css";


//fonts import

const merienda = Merienda(
  {
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800', '900'],
  }
);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
      <html lang="en">
        <body className={`${merienda.className}`}>
          {children}
        </body>
      </html>
    
  );
}
